/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedObrasIndexRouteImport } from './routes/_authenticated/obras.index'
import { Route as AuthenticatedObrasObraIdRouteImport } from './routes/_authenticated/obras.$obraId'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedObrasObraIdTorresTorreIdAndaresAndarIdRouteImport } from './routes/_authenticated/obras.$obraId.torres.$torreId.andares.$andarId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObrasIndexRoute = AuthenticatedObrasIndexRouteImport.update({
  id: '/obras/',
  path: '/obras/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObrasObraIdRoute =
  AuthenticatedObrasObraIdRouteImport.update({
    id: '/obras/$obraId',
    path: '/obras/$obraId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObrasObraIdTorresTorreIdAndaresAndarIdRoute =
  AuthenticatedObrasObraIdTorresTorreIdAndaresAndarIdRouteImport.update({
    id: '/torres/$torreId/andares/$andarId',
    path: '/torres/$torreId/andares/$andarId',
    getParentRoute: () => AuthenticatedObrasObraIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/obras/$obraId': typeof AuthenticatedObrasObraIdRouteWithChildren
  '/obras/': typeof AuthenticatedObrasIndexRoute
  '/obras/$obraId/torres/$torreId/andares/$andarId': typeof AuthenticatedObrasObraIdTorresTorreIdAndaresAndarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/obras/$obraId': typeof AuthenticatedObrasObraIdRouteWithChildren
  '/obras': typeof AuthenticatedObrasIndexRoute
  '/obras/$obraId/torres/$torreId/andares/$andarId': typeof AuthenticatedObrasObraIdTorresTorreIdAndaresAndarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/obras/$obraId': typeof AuthenticatedObrasObraIdRouteWithChildren
  '/_authenticated/obras/': typeof AuthenticatedObrasIndexRoute
  '/_authenticated/obras/$obraId/torres/$torreId/andares/$andarId': typeof AuthenticatedObrasObraIdTorresTorreIdAndaresAndarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/admin/audit'
    | '/admin/usuarios'
    | '/obras/$obraId'
    | '/obras/'
    | '/obras/$obraId/torres/$torreId/andares/$andarId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/admin/audit'
    | '/admin/usuarios'
    | '/obras/$obraId'
    | '/obras'
    | '/obras/$obraId/torres/$torreId/andares/$andarId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/obras/$obraId'
    | '/_authenticated/obras/'
    | '/_authenticated/obras/$obraId/torres/$torreId/andares/$andarId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obras/': {
      id: '/_authenticated/obras/'
      path: '/obras'
      fullPath: '/obras/'
      preLoaderRoute: typeof AuthenticatedObrasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obras/$obraId': {
      id: '/_authenticated/obras/$obraId'
      path: '/obras/$obraId'
      fullPath: '/obras/$obraId'
      preLoaderRoute: typeof AuthenticatedObrasObraIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obras/$obraId/torres/$torreId/andares/$andarId': {
      id: '/_authenticated/obras/$obraId/torres/$torreId/andares/$andarId'
      path: '/torres/$torreId/andares/$andarId'
      fullPath: '/obras/$obraId/torres/$torreId/andares/$andarId'
      preLoaderRoute: typeof AuthenticatedObrasObraIdTorresTorreIdAndaresAndarIdRouteImport
      parentRoute: typeof AuthenticatedObrasObraIdRoute
    }
  }
}

interface AuthenticatedObrasObraIdRouteChildren {
  AuthenticatedObrasObraIdTorresTorreIdAndaresAndarIdRoute: typeof AuthenticatedObrasObraIdTorresTorreIdAndaresAndarIdRoute
}

const AuthenticatedObrasObraIdRouteChildren: AuthenticatedObrasObraIdRouteChildren =
  {
    AuthenticatedObrasObraIdTorresTorreIdAndaresAndarIdRoute:
      AuthenticatedObrasObraIdTorresTorreIdAndaresAndarIdRoute,
  }

const AuthenticatedObrasObraIdRouteWithChildren =
  AuthenticatedObrasObraIdRoute._addFileChildren(
    AuthenticatedObrasObraIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedObrasObraIdRoute: typeof AuthenticatedObrasObraIdRouteWithChildren
  AuthenticatedObrasIndexRoute: typeof AuthenticatedObrasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedObrasObraIdRoute: AuthenticatedObrasObraIdRouteWithChildren,
  AuthenticatedObrasIndexRoute: AuthenticatedObrasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
