/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRhRouteImport } from './routes/_authenticated/rh'
import { Route as AuthenticatedPatrimonioRouteImport } from './routes/_authenticated/patrimonio'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedHubRouteImport } from './routes/_authenticated/hub'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedDiretoriaRouteImport } from './routes/_authenticated/diretoria'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated/compras'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedObrasIndexRouteImport } from './routes/_authenticated/obras.index'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedObrasObraIdRouteImport } from './routes/_authenticated/obras.$obraId'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminBackupRouteImport } from './routes/_authenticated/admin.backup'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedObrasObraIdTorresTorreIdRouteImport } from './routes/_authenticated/obras.$obraId.torres.$torreId'
import { Route as AuthenticatedObrasObraIdRdosRdoIdRouteImport } from './routes/_authenticated/obras.$obraId.rdos.$rdoId'
import { Route as AuthenticatedObrasObraIdTorresTorreIdPavimentosPavimentoIdRouteImport } from './routes/_authenticated/obras.$obraId.torres.$torreId.pavimentos.$pavimentoId'
import { Route as AuthenticatedObrasObraIdTorresTorreIdAndaresAndarIdRouteImport } from './routes/_authenticated/obras.$obraId.torres.$torreId.andares.$andarId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRhRoute = AuthenticatedRhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatrimonioRoute = AuthenticatedPatrimonioRouteImport.update({
  id: '/patrimonio',
  path: '/patrimonio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHubRoute = AuthenticatedHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiretoriaRoute = AuthenticatedDiretoriaRouteImport.update({
  id: '/diretoria',
  path: '/diretoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObrasIndexRoute = AuthenticatedObrasIndexRouteImport.update({
  id: '/obras/',
  path: '/obras/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedObrasObraIdRoute =
  AuthenticatedObrasObraIdRouteImport.update({
    id: '/obras/$obraId',
    path: '/obras/$obraId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBackupRoute =
  AuthenticatedAdminBackupRouteImport.update({
    id: '/admin/backup',
    path: '/admin/backup',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObrasObraIdTorresTorreIdRoute =
  AuthenticatedObrasObraIdTorresTorreIdRouteImport.update({
    id: '/torres/$torreId',
    path: '/torres/$torreId',
    getParentRoute: () => AuthenticatedObrasObraIdRoute,
  } as any)
const AuthenticatedObrasObraIdRdosRdoIdRoute =
  AuthenticatedObrasObraIdRdosRdoIdRouteImport.update({
    id: '/rdos/$rdoId',
    path: '/rdos/$rdoId',
    getParentRoute: () => AuthenticatedObrasObraIdRoute,
  } as any)
const AuthenticatedObrasObraIdTorresTorreIdPavimentosPavimentoIdRoute =
  AuthenticatedObrasObraIdTorresTorreIdPavimentosPavimentoIdRouteImport.update({
    id: '/pavimentos/$pavimentoId',
    path: '/pavimentos/$pavimentoId',
    getParentRoute: () => AuthenticatedObrasObraIdTorresTorreIdRoute,
  } as any)
const AuthenticatedObrasObraIdTorresTorreIdAndaresAndarIdRoute =
  AuthenticatedObrasObraIdTorresTorreIdAndaresAndarIdRouteImport.update({
    id: '/andares/$andarId',
    path: '/andares/$andarId',
    getParentRoute: () => AuthenticatedObrasObraIdTorresTorreIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diretoria': typeof AuthenticatedDiretoriaRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/hub': typeof AuthenticatedHubRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/patrimonio': typeof AuthenticatedPatrimonioRoute
  '/rh': typeof AuthenticatedRhRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/obras/$obraId': typeof AuthenticatedObrasObraIdRouteWithChildren
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/obras/': typeof AuthenticatedObrasIndexRoute
  '/obras/$obraId/rdos/$rdoId': typeof AuthenticatedObrasObraIdRdosRdoIdRoute
  '/obras/$obraId/torres/$torreId': typeof AuthenticatedObrasObraIdTorresTorreIdRouteWithChildren
  '/obras/$obraId/torres/$torreId/andares/$andarId': typeof AuthenticatedObrasObraIdTorresTorreIdAndaresAndarIdRoute
  '/obras/$obraId/torres/$torreId/pavimentos/$pavimentoId': typeof AuthenticatedObrasObraIdTorresTorreIdPavimentosPavimentoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diretoria': typeof AuthenticatedDiretoriaRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/hub': typeof AuthenticatedHubRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/patrimonio': typeof AuthenticatedPatrimonioRoute
  '/rh': typeof AuthenticatedRhRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/obras/$obraId': typeof AuthenticatedObrasObraIdRouteWithChildren
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/obras': typeof AuthenticatedObrasIndexRoute
  '/obras/$obraId/rdos/$rdoId': typeof AuthenticatedObrasObraIdRdosRdoIdRoute
  '/obras/$obraId/torres/$torreId': typeof AuthenticatedObrasObraIdTorresTorreIdRouteWithChildren
  '/obras/$obraId/torres/$torreId/andares/$andarId': typeof AuthenticatedObrasObraIdTorresTorreIdAndaresAndarIdRoute
  '/obras/$obraId/torres/$torreId/pavimentos/$pavimentoId': typeof AuthenticatedObrasObraIdTorresTorreIdPavimentosPavimentoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diretoria': typeof AuthenticatedDiretoriaRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/hub': typeof AuthenticatedHubRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/patrimonio': typeof AuthenticatedPatrimonioRoute
  '/_authenticated/rh': typeof AuthenticatedRhRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/obras/$obraId': typeof AuthenticatedObrasObraIdRouteWithChildren
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/obras/': typeof AuthenticatedObrasIndexRoute
  '/_authenticated/obras/$obraId/rdos/$rdoId': typeof AuthenticatedObrasObraIdRdosRdoIdRoute
  '/_authenticated/obras/$obraId/torres/$torreId': typeof AuthenticatedObrasObraIdTorresTorreIdRouteWithChildren
  '/_authenticated/obras/$obraId/torres/$torreId/andares/$andarId': typeof AuthenticatedObrasObraIdTorresTorreIdAndaresAndarIdRoute
  '/_authenticated/obras/$obraId/torres/$torreId/pavimentos/$pavimentoId': typeof AuthenticatedObrasObraIdTorresTorreIdPavimentosPavimentoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/compras'
    | '/dashboard'
    | '/diretoria'
    | '/financeiro'
    | '/hub'
    | '/notes'
    | '/patrimonio'
    | '/rh'
    | '/admin/audit'
    | '/admin/backup'
    | '/admin/usuarios'
    | '/obras/$obraId'
    | '/settings/profile'
    | '/obras/'
    | '/obras/$obraId/rdos/$rdoId'
    | '/obras/$obraId/torres/$torreId'
    | '/obras/$obraId/torres/$torreId/andares/$andarId'
    | '/obras/$obraId/torres/$torreId/pavimentos/$pavimentoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/compras'
    | '/dashboard'
    | '/diretoria'
    | '/financeiro'
    | '/hub'
    | '/notes'
    | '/patrimonio'
    | '/rh'
    | '/admin/audit'
    | '/admin/backup'
    | '/admin/usuarios'
    | '/obras/$obraId'
    | '/settings/profile'
    | '/obras'
    | '/obras/$obraId/rdos/$rdoId'
    | '/obras/$obraId/torres/$torreId'
    | '/obras/$obraId/torres/$torreId/andares/$andarId'
    | '/obras/$obraId/torres/$torreId/pavimentos/$pavimentoId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calendar'
    | '/_authenticated/compras'
    | '/_authenticated/dashboard'
    | '/_authenticated/diretoria'
    | '/_authenticated/financeiro'
    | '/_authenticated/hub'
    | '/_authenticated/notes'
    | '/_authenticated/patrimonio'
    | '/_authenticated/rh'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/backup'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/obras/$obraId'
    | '/_authenticated/settings/profile'
    | '/_authenticated/obras/'
    | '/_authenticated/obras/$obraId/rdos/$rdoId'
    | '/_authenticated/obras/$obraId/torres/$torreId'
    | '/_authenticated/obras/$obraId/torres/$torreId/andares/$andarId'
    | '/_authenticated/obras/$obraId/torres/$torreId/pavimentos/$pavimentoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rh': {
      id: '/_authenticated/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof AuthenticatedRhRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patrimonio': {
      id: '/_authenticated/patrimonio'
      path: '/patrimonio'
      fullPath: '/patrimonio'
      preLoaderRoute: typeof AuthenticatedPatrimonioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hub': {
      id: '/_authenticated/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AuthenticatedHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diretoria': {
      id: '/_authenticated/diretoria'
      path: '/diretoria'
      fullPath: '/diretoria'
      preLoaderRoute: typeof AuthenticatedDiretoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obras/': {
      id: '/_authenticated/obras/'
      path: '/obras'
      fullPath: '/obras/'
      preLoaderRoute: typeof AuthenticatedObrasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obras/$obraId': {
      id: '/_authenticated/obras/$obraId'
      path: '/obras/$obraId'
      fullPath: '/obras/$obraId'
      preLoaderRoute: typeof AuthenticatedObrasObraIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/backup': {
      id: '/_authenticated/admin/backup'
      path: '/admin/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AuthenticatedAdminBackupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obras/$obraId/torres/$torreId': {
      id: '/_authenticated/obras/$obraId/torres/$torreId'
      path: '/torres/$torreId'
      fullPath: '/obras/$obraId/torres/$torreId'
      preLoaderRoute: typeof AuthenticatedObrasObraIdTorresTorreIdRouteImport
      parentRoute: typeof AuthenticatedObrasObraIdRoute
    }
    '/_authenticated/obras/$obraId/rdos/$rdoId': {
      id: '/_authenticated/obras/$obraId/rdos/$rdoId'
      path: '/rdos/$rdoId'
      fullPath: '/obras/$obraId/rdos/$rdoId'
      preLoaderRoute: typeof AuthenticatedObrasObraIdRdosRdoIdRouteImport
      parentRoute: typeof AuthenticatedObrasObraIdRoute
    }
    '/_authenticated/obras/$obraId/torres/$torreId/pavimentos/$pavimentoId': {
      id: '/_authenticated/obras/$obraId/torres/$torreId/pavimentos/$pavimentoId'
      path: '/pavimentos/$pavimentoId'
      fullPath: '/obras/$obraId/torres/$torreId/pavimentos/$pavimentoId'
      preLoaderRoute: typeof AuthenticatedObrasObraIdTorresTorreIdPavimentosPavimentoIdRouteImport
      parentRoute: typeof AuthenticatedObrasObraIdTorresTorreIdRoute
    }
    '/_authenticated/obras/$obraId/torres/$torreId/andares/$andarId': {
      id: '/_authenticated/obras/$obraId/torres/$torreId/andares/$andarId'
      path: '/andares/$andarId'
      fullPath: '/obras/$obraId/torres/$torreId/andares/$andarId'
      preLoaderRoute: typeof AuthenticatedObrasObraIdTorresTorreIdAndaresAndarIdRouteImport
      parentRoute: typeof AuthenticatedObrasObraIdTorresTorreIdRoute
    }
  }
}

interface AuthenticatedObrasObraIdTorresTorreIdRouteChildren {
  AuthenticatedObrasObraIdTorresTorreIdAndaresAndarIdRoute: typeof AuthenticatedObrasObraIdTorresTorreIdAndaresAndarIdRoute
  AuthenticatedObrasObraIdTorresTorreIdPavimentosPavimentoIdRoute: typeof AuthenticatedObrasObraIdTorresTorreIdPavimentosPavimentoIdRoute
}

const AuthenticatedObrasObraIdTorresTorreIdRouteChildren: AuthenticatedObrasObraIdTorresTorreIdRouteChildren =
  {
    AuthenticatedObrasObraIdTorresTorreIdAndaresAndarIdRoute:
      AuthenticatedObrasObraIdTorresTorreIdAndaresAndarIdRoute,
    AuthenticatedObrasObraIdTorresTorreIdPavimentosPavimentoIdRoute:
      AuthenticatedObrasObraIdTorresTorreIdPavimentosPavimentoIdRoute,
  }

const AuthenticatedObrasObraIdTorresTorreIdRouteWithChildren =
  AuthenticatedObrasObraIdTorresTorreIdRoute._addFileChildren(
    AuthenticatedObrasObraIdTorresTorreIdRouteChildren,
  )

interface AuthenticatedObrasObraIdRouteChildren {
  AuthenticatedObrasObraIdRdosRdoIdRoute: typeof AuthenticatedObrasObraIdRdosRdoIdRoute
  AuthenticatedObrasObraIdTorresTorreIdRoute: typeof AuthenticatedObrasObraIdTorresTorreIdRouteWithChildren
}

const AuthenticatedObrasObraIdRouteChildren: AuthenticatedObrasObraIdRouteChildren =
  {
    AuthenticatedObrasObraIdRdosRdoIdRoute:
      AuthenticatedObrasObraIdRdosRdoIdRoute,
    AuthenticatedObrasObraIdTorresTorreIdRoute:
      AuthenticatedObrasObraIdTorresTorreIdRouteWithChildren,
  }

const AuthenticatedObrasObraIdRouteWithChildren =
  AuthenticatedObrasObraIdRoute._addFileChildren(
    AuthenticatedObrasObraIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiretoriaRoute: typeof AuthenticatedDiretoriaRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedHubRoute: typeof AuthenticatedHubRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedPatrimonioRoute: typeof AuthenticatedPatrimonioRoute
  AuthenticatedRhRoute: typeof AuthenticatedRhRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBackupRoute: typeof AuthenticatedAdminBackupRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedObrasObraIdRoute: typeof AuthenticatedObrasObraIdRouteWithChildren
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedObrasIndexRoute: typeof AuthenticatedObrasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiretoriaRoute: AuthenticatedDiretoriaRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedHubRoute: AuthenticatedHubRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedPatrimonioRoute: AuthenticatedPatrimonioRoute,
  AuthenticatedRhRoute: AuthenticatedRhRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBackupRoute: AuthenticatedAdminBackupRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedObrasObraIdRoute: AuthenticatedObrasObraIdRouteWithChildren,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedObrasIndexRoute: AuthenticatedObrasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
